### ISSUE TITLE
Cannot get the code to work

### ISSUE THREAD

**Issue by MojoMoe** [umd-coding-workshop/ics-to-csv#1]
Please let me know if I am not doing this right:

`PS C:\Users\Moe\Desktop\PowerShell_Scripts\ics-to-csv> pip install ics 

Requirement already satisfied: ics in c:\python311\lib\site-packages (0.7.2)
Requirement already satisfied: python-dateutil in c:\python311\lib\site-packages (from ics) (2.8.0)
Requirement already satisfied: arrow>=0.11 in c:\python311\lib\site-packages (from ics) (1.2.3)
Requirement already satisfied: six>1.5 in c:\python311\lib\site-packages (from ics) (1.12.0)
Requirement already satisfied: tatsu>4.2 in c:\python311\lib\site-packages (from ics) (5.8.3)
Requirement already satisfied: attrs>=19.1.0 in c:\python311\lib\site-packages (from ics) (22.2.0)

PS C:\Users\Moe\Desktop\PowerShell_Scripts\ics-to-csv> python3 .\ics_to_csv.py .\test1.ics
Traceback (most recent call last):
  File "C:\Users\Moe\Desktop\PowerShell_Scripts\ics-to-csv\ics_to_csv.py", line 5, in <module>
    from ics import Calendar
ModuleNotFoundError: No module named 'ics'

PS C:\Users\Moe\Desktop\PowerShell_Scripts\ics-to-csv>`

**Comment by jwestgard** [comment]
My guess would be that the pip command is not installing the dependencies in the same copy of python that you are attempting to run the code against. You can work around this by running pip as a module with the python you routinely use:

`python3 -m pip install ics`

**Comment by MojoMoe** [comment]
> My guess would be that the pip command is not installing the dependencies in the same copy of python that you are attempting to run the code against. You can work around this by running pip as a module with the python you routinely use:
> 
> `python3 -m pip install ics`

Thank you, that seems to have fixed the issue. Much appreciated :)
